### PR TITLE
Upgrade Scala to 2.13

### PR DESCRIPTION
**Pull request by lavrov**

### CODE REVIEW

**Comment by TimWSpence** [comment]
Hey @lavrov did you mean to mark this PR as a draft?

**Comment by lavrov** [comment]
`docs` module doesn't compile because some dependencies are not published for 2.13 (e.g [github4s](https://github.com/47deg/github4s/pull/262)). I could reorganize the build so that docs would not depend on scala version. Do you think it makes sense?

**Comment by TimWSpence** [comment]
Oh yes, I remember that now! I had a very quick look at supporting 2.13 and had the same issue. I think it's probably a bit dodgy to make the docs not depend on scala version, given that the docs should work for the supported scala version! Or maybe I've misunderstood your suggestion!

It looks like 2.13 support might be coming soon for Github4s so I think I'm happy to wait for that?

Out of curiousity: are you using this library for anything at the moment? Keen to hear feedback from any users! :)

**Comment by lavrov** [comment]
Compiling and running `tut` samples in `docs` with all supported version of Scala makes sense. However it's unfortunate that `github4s` is a compile-time dependency of that module. Probably the issue with `github4s` will be resolved soon.

> Out of curiousity: are you using this library for anything at the moment? Keen to hear feedback from any users! :)

There is quite trivial use [here](https://github.com/lavrov/bittorrent/blob/master/bittorrent/src/com/github/lavrov/bittorrent/ConnectionManager.scala#L53). I find the api quite expressive and intuitive. I especially like `STM.check(...)` which makes the whole difference compared to `Ref` or `MVar`.

**Comment by juanpedromoreno** [comment]
Just in case this helps, as mentioned here: https://github.com/47deg/github4s/issues/261, if you have issues in the docs module, you could follow this path temporarily:

> Present workaround is to exclude docs from aggregated build, and only run docs commands on scala <= 2.12

**Comment by lavrov** [comment]
One test started failing after Scalacheck `1.14.1` upgrade. All tests pass on `1.14.0`

**Comment by Jacke** [comment]
+++++++++=

**Comment by TimWSpence** [comment]
Sorry all, I've been a bit busy! Yes, I'm aware the tests have been failing 😭I'll fix that and then look into this. Would love to get 2.13 supported!

**Comment by TimWSpence** [comment]
Ok I've rolled back the scalatest version. @lavrov could you rebase your PR? Thanks very much! :)

**Comment by lavrov** [comment]
@TimWSpence done! I have updated `.travis` as well.

**Comment by TimWSpence** [comment]
Awesome, thanks @lavrov! :) I'll try to make a new release this afternoon

**Pull request merged**
