### PR TITLE
fixes #137 compilation problem on github.io, get rid of ;

### LINKED ISSUE #137: santa claus example on github.io does not compile
Hi, thanks for the library !

I was going through the tutorial, but the code published on `github.io` does not compile.   

If you copy the code directly from https://github.com/TimWSpence/cats-stm/blob/master/docs/docs/tutorial/tutorial.md it works just fine, but it seems the publish process to `github.io` gets confused by the `;` instances in the code.

This : 
```scala
}; object Gate{
```

somehow gets translated to 

```scala
}; object Gate{; object Gate{
```

on `github.io`

I'm guessing getting rid of the `;` and putting the companion object on a separate line will fix the issue.

Let me know if you'd like me to submit a PR, I'm happy to do so.

### PR DESCRIPTION
**Pull request by alexandervanhecke**

### CODE REVIEW

**Comment by TimWSpence** [comment]
Thanks @alexandervanhecke! That looks like some very suspicious formatting. Where is the compilation problem you referred to sorry?

**Comment by alexandervanhecke** [comment]
@TimWSpence if you copy paste the code from the documentation found on github.io it doesn't compile

**Comment by TimWSpence** [comment]
@alexandervanhecke what compilation error do you get? mdoc should compile the examples and I also tried it locally and had no problems. I'm happy to merge this anyway because the current formatting is nasty but I'm curious what error you're seeing

**Comment by TimWSpence** [comment]
Also sorry for the delay in replying!

**Comment by alexandervanhecke** [comment]
@TimWSpence to clarify what I did : 
- clicked on the documentation link found in this repo
- got to the tutorial here : https://timwspence.github.io/cats-stm/tutorial/tutorial.html
- copy pasted the code of that tutorial in a new file (contained in an `object SantaClaus extends App`)

this fails to compile : 
```scala
[error] /Users/alexander/github/test-stm/src/main/scala/be/avhconsult/SantaClaus.scala:40:3: Missing closing brace `}` assumed here
[error]   }
[error]   ^
[error] /Users/alexander/github/test-stm/src/main/scala/be/avhconsult/SantaClaus.scala:71:5: Missing closing brace `}` assumed here
[error]     }
[error]     ^
[error] two errors found
```

the missing close brace is because of the lines containing two semicolons `}; object Gate{; object Gate{` and `}; object Group {; object Group {`

deleting one of the superfluous `object Gate{;`instances fixes this.  in fact, no semicolon is needed at all.

wkr,
Alexander

**Comment by TimWSpence** [comment]
@alexandervanhecke hmm that's strange... That's what I tried and I had no problems. Anyway, it's a good change so thanks very much! :)

**Pull request merged**
